# Generated by Django 5.1.1 on 2025-01-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DemoModel', to='myapp.demomodel'),
        ),
    ]
